# Generated by Django 3.0.4 on 2020-04-01 11:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Facility Name')),
                ('desc', models.TextField(blank=True, default='-', verbose_name='Description')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Build')),
                ('type', models.CharField(choices=[('GN', 'General'), ('OF', 'Office'), ('SH', 'Shop'), ('RS', 'Restaurant'), ('PR', 'Pray'), ('AT', 'Attraction')], max_length=3, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'db_table': 'facility',
            },
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Collection Name')),
                ('desc', models.TextField(blank=True, default='-', verbose_name='Description')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Build')),
            ],
            options={
                'verbose_name': 'Garden',
                'verbose_name_plural': 'Gardens',
                'db_table': 'garden',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('content', models.TextField(blank=True, default='-', verbose_name='Content')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Species Name')),
                ('family', models.CharField(blank=True, default='-', max_length=60, verbose_name='Family Name')),
                ('local', models.CharField(blank=True, default='-', max_length=100, verbose_name='Local Name')),
                ('synonym', models.CharField(blank=True, default='-', max_length=200, verbose_name='Synonym Name')),
                ('characteristic', models.TextField(blank=True, default='-', verbose_name='Characteristic')),
                ('image', models.ImageField(blank=True, upload_to='images/plants', verbose_name='Picture')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.Garden')),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'db_table': 'plant',
            },
        ),
    ]
