# Generated by Django 3.0.4 on 2020-04-03 08:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Collection Name')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Build')),
            ],
            options={
                'verbose_name': 'Garden',
                'verbose_name_plural': 'Gardens',
                'db_table': 'garden',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Species Name')),
                ('family', models.CharField(blank=True, max_length=60, verbose_name='Family Name')),
                ('local', models.CharField(blank=True, max_length=100, verbose_name='Local Name')),
                ('synonym', models.CharField(blank=True, max_length=200, verbose_name='Synonym Name')),
                ('characteristic', models.TextField(blank=True, verbose_name='Characteristic')),
                ('image', models.ImageField(blank=True, upload_to='images/plants', verbose_name='Picture')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.Garden')),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'db_table': 'plant',
            },
        ),
    ]
