# Generated by Django 3.0.4 on 2020-04-05 13:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Botanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Build')),
                ('image', models.ImageField(blank=True, upload_to='images/botanics', verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'Botanic',
                'verbose_name_plural': 'Botanics',
                'db_table': 'botanic',
            },
        ),
        migrations.RemoveField(
            model_name='plant',
            name='garden',
        ),
        migrations.AddField(
            model_name='plant',
            name='gardens',
            field=models.ManyToManyField(blank=True, related_name='plants', to='plant.Garden'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Collection Name'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, upload_to='images/categories', verbose_name='Picture')),
                ('plants', models.ManyToManyField(blank=True, related_name='categories', to='plant.Plant')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.AddField(
            model_name='garden',
            name='botanic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plant.Botanic'),
        ),
    ]
