# Generated by Django 3.0.4 on 2020-04-15 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_auto_20200405_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='botanic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to='plant.Botanic'),
        ),
    ]
