# Generated by Django 3.0.4 on 2020-04-18 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_auto_20200416_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='botanic',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='family',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='origin',
        ),
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added'),
        ),
        migrations.AddField(
            model_name='garden',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/gardens', verbose_name='Picture'),
        ),
        migrations.AddField(
            model_name='garden',
            name='location_lat',
            field=models.FloatField(blank=True, default=0, verbose_name='Latitude Location'),
        ),
        migrations.AddField(
            model_name='garden',
            name='location_long',
            field=models.FloatField(blank=True, default=0, verbose_name='Longitude Location'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added'),
        ),
        migrations.DeleteModel(
            name='Botanic',
        ),
    ]
