# Generated by Django 3.0.4 on 2020-04-18 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0008_auto_20200418_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='more_photos', to='plant.Plant'),
        ),
    ]
